#!/bin/bash
# Compile the RSX Cg shaders with cgcomp and embed the resulting vpo/fpo
# microcode as C arrays in Ps3Shaders_gen.h, so the graphics backend can link
# them in without a Makefile shader-compile step. Re-run this whenever a
# .vcg/.fcg changes (from WSL: bash gen_shaders.sh). Requires ps3dev's cgcomp,
# which dlopens NVIDIA's libCg.so — point CG_LIB_DIR at a dir containing it
# (the NVIDIA Cg Toolkit for Linux; the toolchain ships cgdll-installer.sh for
# the Windows cg.dll equivalent).
set -e
CG=/usr/local/ps3dev/bin/cgcomp
CG_LIB_DIR="${CG_LIB_DIR:-/tmp/cgtk/usr/lib64}"
export LD_LIBRARY_PATH="$CG_LIB_DIR:$LD_LIBRARY_PATH"
DIR="$(cd "$(dirname "$0")" && pwd)"
OUT="$DIR/Ps3Shaders_gen.h"
TMP="$(mktemp -d)"

emit_array() {
    # $1 = symbol name, $2 = binary file
    local name="$1" file="$2"
    printf 'static const unsigned char %s[] __attribute__((aligned(16))) = {\n' "$name"
    # Emit 20 comma-separated values per line. Break BETWEEN values only (never
    # mid-number, which would create invalid octal like "08").
    od -An -v -tu1 "$file" | awk '{ for (i=1;i<=NF;i++) { printf "%s,", $i; if (++n % 20 == 0) printf "\n"; } } END { if (n % 20) printf "\n"; }'
    printf '};\n'
    printf 'static const unsigned int %s_size = %d;\n\n' "$name" "$(stat -c%s "$file")"
}

{
    echo "// GENERATED by gen_shaders.sh — do not edit. Source: ps3_*.vcg / ps3_*.fcg"
    echo "#pragma once"
    echo
    "$CG" -v "$DIR/ps3_ui.vcg"   "$TMP/ps3_ui_vpo"   >/dev/null
    "$CG" -f "$DIR/ps3_ui.fcg"   "$TMP/ps3_ui_fpo"   >/dev/null
    "$CG" -v "$DIR/ps3_mesh.vcg" "$TMP/ps3_mesh_vpo" >/dev/null
    "$CG" -f "$DIR/ps3_mesh.fcg" "$TMP/ps3_mesh_fpo" >/dev/null
    emit_array ps3_ui_vpo   "$TMP/ps3_ui_vpo"
    emit_array ps3_ui_fpo   "$TMP/ps3_ui_fpo"
    emit_array ps3_mesh_vpo "$TMP/ps3_mesh_vpo"
    emit_array ps3_mesh_fpo "$TMP/ps3_mesh_fpo"
} > "$OUT"

rm -rf "$TMP"
echo "Wrote $OUT"
