/**
 * @file Main_PS3.cpp
 * @brief PS3 entry point — boots the engine, runs the main loop, exits clean.
 *
 * Mirrors the desktop Standalone/Source/Main.cpp boot sequence (Oct* hooks →
 * GameMain). PSL1GHT uses a plain `int main(int, char**)` entry, so unlike the
 * PSP port there is no module-info macro to declare — the fself/pkg tooling
 * reads the ELF directly.
 *
 * The engine's own `int main` is gated out when POLYPHASE_PLATFORM_ADDON is
 * defined (small arm in Engine.cpp), so the main below is the sole entry.
 *
 * Oct* hooks below are stubs — a BuildTarget test project doesn't supply its
 * own Main.cpp, so we provide minimal versions. Real game projects targeting
 * PS3 can override by defining their own under Source/.
 */

#if defined(POLYPHASE_PLATFORM_ADDON)

#include <ppu-types.h>
#include <lv2/sysfs.h>
#include <sys/tty.h>
#include <sys/process.h>

// PS3 process parameters: primary PPU thread priority + stack size. Every real
// PS3 app declares this (the PSL1GHT samples use SYS_PROCESS_PARAM(1001,
// 0x100000)); without it the process/RSX setup is inconsistent under RPCS3.
// Stack: the engine's C++ + Lua load/run chains (Initialize -> script load ->
// lua_pcall -> engine bindings) recurse deeply on the primary thread, so use a
// generous 16 MB stack — a too-small stack segfaults inside lua_pcall while
// loading the game scripts (GameState.lua).
SYS_PROCESS_PARAM(1001, 0x1000000);

#include <stdio.h>
#include <string.h>
#include <exception>
#include <cxxabi.h>

#include "Engine.h"
#include "EmbeddedFile.h"
#include "Log.h"

// Embedded-scripts table generated by the editor's packager into
// Generated/EmbeddedScripts.cpp at cook time. Wired into the EngineConfig in
// OctPreInitialize (mirroring Standalone/Source/Main.cpp) so Lua-attached
// components actually run — the runtime has no disk-side Scripts/ folder for
// embedded builds.
extern uint32_t gNumEmbeddedScripts;
extern EmbeddedFile gEmbeddedScripts[];

// C++ pure-virtual-call handler. With -fno-exceptions -fno-rtti the PPU link
// never pulls libsupc++'s copy in, leaving __cxa_pure_virtual UNDEFINED, and
// every abstract-class vtable slot carries a relocation against the null
// section. Enough of those and the loader rejects the SELF. Define it here so
// those relocations resolve and the module loads. (Same class of bug the PSP
// port hit — see Main_PSP.cpp.)
// Unbuffered TTY write (lv2 syscall) — safe from static-init / abort context.
static void Ps3TtyRaw(const char* s)
{
    if (s == nullptr) return;
    u32 w = 0;
    sysTtyWrite(0, s, (u32)strlen(s), &w);
}

extern "C" void __cxa_pure_virtual()
{
    Ps3TtyRaw("[FATAL] __cxa_pure_virtual (pure virtual call)\n");
    for (;;) {}
}

// The engine boots with -fno-exceptions, so any libstdc++ call that THROWS
// (std::vector::at, std::stoi, std::string over-size, bad_alloc, a static
// std::regex, ...) turns into std::terminate -> abort. The RPCS3 run showed
// "Abort called." with NONE of our checkpoints before it, which means a GLOBAL
// CONSTRUCTOR is throwing before main() runs. These handlers print WHAT threw
// (mangled type name) and WHERE an abort came from, so we can pinpoint it.
static void Ps3TerminateHandler()
{
    const std::type_info* t = abi::__cxa_current_exception_type();
    char buf[160];
    std::snprintf(buf, sizeof(buf),
                  "[TERMINATE] uncaught exception, type = %s\n",
                  t ? t->name() : "(no active exception)");
    Ps3TtyRaw(buf);
    for (;;) {}
}

extern "C" void abort(void)
{
    char buf[160];
    std::snprintf(buf, sizeof(buf), "[ABORT] abort() called. RA0=%p RA1=%p\n",
                  __builtin_return_address(0), __builtin_return_address(1));
    Ps3TtyRaw(buf);
    for (;;) {}
}

// newlib's assert() macro routes here. Override it so a failing assert prints
// its file/line/expression to TTY instead of a silent abort — this is the most
// likely cause of the pre-main abort (an External lib — Bullet/recast/Lua — or
// engine global ctor tripping an assert).
extern "C" void __assert_func(const char* file, int line, const char* func, const char* expr)
{
    char buf[256];
    std::snprintf(buf, sizeof(buf), "[ASSERT] %s:%d  %s()  ->  %s\n",
                  file ? file : "?", line, func ? func : "?", expr ? expr : "?");
    Ps3TtyRaw(buf);
    for (;;) {}
}

// -fstack-protector trip lands here.
extern "C" void __stack_chk_fail(void)
{
    Ps3TtyRaw("[STACK_CHK_FAIL] stack smashing detected\n");
    for (;;) {}
}

// Runs at global-construction time, at a HIGH priority (101) so it executes
// before the engine's default-priority static initializers — installs the
// terminate handler and proves static init started.
__attribute__((constructor(101)))
static void Ps3InstallDiagnostics()
{
    std::set_terminate(&Ps3TerminateHandler);
    Ps3TtyRaw("[E] early-ctor: diagnostics installed\n");
}

// Ordinary-priority static-init canary — runs with the engine's own global
// ctors. If "[E]" prints but this "[0]" does not, an engine static initializer
// between them is what aborts.
namespace
{
    struct Ps3BootCanary
    {
        Ps3BootCanary() { Ps3TtyRaw("[0] static-init reached\n"); }
    } sPs3BootCanary;
}

// -------------------------------------------------------------------------
// Boot-checkpoint log — independent of the engine's SYS_Log so it works
// BEFORE Initialize() runs. Writes to /dev_hdd0/tmp/ (always writable on real
// firmware and under RPCS3) plus stdout (captured by RPCS3's TTY log).
// -------------------------------------------------------------------------

// HDD root, not /dev_hdd0/tmp — sysFsOpen(O_CREAT) creates the file but not a
// missing parent dir, and RPCS3's virtual HDD has no /dev_hdd0/tmp by default,
// so writing there silently failed and produced no trace. The root always
// exists and is writable (appears at <RPCS3>/dev_hdd0/polyphase_ps3.log).
static const char* kBootLogPath = "/dev_hdd0/polyphase_ps3.log";

// RPCS3 captures the lv2 sys_tty_write syscall in its TTY window (and log with
// a "TTY:" prefix), regardless of how newlib wires stdout — the reliable
// diagnostic channel on emulator + real hardware.
static void Ps3_Tty(const char* s)
{
    if (s == nullptr) return;
    u32 written = 0;
    sysTtyWrite(0, s, (u32)strlen(s), &written);
}

static void Ps3_BootLogRaw(const char* msg, bool /*truncate*/)
{
    // TTY (+ stdout) only — /dev_hdd0 root is not writable under RPCS3
    // (cellFsOpen -> CELL_EACCES), so the file write just spams errors.
    if (msg == nullptr) return;
    fputs(msg, stdout); fputc('\n', stdout); fflush(stdout);
    Ps3_Tty(msg); Ps3_Tty("\n");
}

static void Ps3_BootLog(const char* msg) { Ps3_BootLogRaw(msg, false); }

// -------------------------------------------------------------------------
// Oct* hooks — minimal stubs. Engine/Source/Engine/OctHookAutoRegister.cpp
// resolves these externs at static-init time and forwards them through
// RegisterOctHooks(), so the engine sees them as the game's hooks.
// -------------------------------------------------------------------------

void OctPreInitialize(EngineConfig& config)
{
    GetEngineState()->mStandalone = true;

    // Force 720p logical size. Both the EngineConfig (checked by most code)
    // and — after ReadEngineConfig reloads Config.ini — the EngineState copy
    // in OctPostInitialize must be set (see comment there).
    config.mWindowWidth  = 1280;
    config.mWindowHeight = 720;

    config.mEmbeddedScriptCount = gNumEmbeddedScripts;
    config.mEmbeddedScripts     = gEmbeddedScripts;
}

void OctPostInitialize()
{
    // OctPreInitialize sets the config BEFORE GameMain's ReadEngineConfig()
    // loads Config.ini, which can overwrite our size with whatever the project
    // authored for desktop. Initialize() then copies the (possibly clobbered)
    // config into EngineState. Renderer::GetViewportWidth/Height reads
    // EngineState live every frame, so re-force here — AFTER ReadEngineConfig
    // and the config→state copy — to keep widget sizing correct.
    const uint32_t beforeW = GetEngineState()->mWindowWidth;
    const uint32_t beforeH = GetEngineState()->mWindowHeight;
    GetEngineState()->mWindowWidth  = 1280;
    GetEngineState()->mWindowHeight = 720;
    LogDebug("[PS3] OctPostInitialize: window %ux%u -> 1280x720", beforeW, beforeH);
}
void OctPreUpdate() {}
void OctPostUpdate() {}
void OctPreShutdown() {}
void OctPostShutdown() {}

// -------------------------------------------------------------------------
// Engine entry. GameMain is defined inside Engine/Source/Engine/Engine.cpp
// and bundles ReadCommandLineArgs → OctPreInitialize → Initialize →
// OctPostInitialize → loop(Update) → Shutdown. We just call it.
// -------------------------------------------------------------------------

extern void GameMain(int32_t argc, char** argv);

int main(int argc, char** argv)
{
    Ps3_BootLogRaw("=== Polyphase PS3 boot log ===", /*truncate=*/true);
    Ps3_BootLog("[1] main() entered");

    Ps3_BootLog("[2] About to call GameMain()");
    GameMain(argc, argv);
    Ps3_BootLog("[3] GameMain() returned cleanly");

    return 0;
}

#endif // POLYPHASE_PLATFORM_ADDON
